server: 
  port: 8091
spring: 
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoelZG/configuraciones-yml.git
          username: 
          password: 
          default-label: main
  profiles:
    active: git
          
         